services:
  # Go    
  golang:
    container_name: go
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/go/src
    ports:
      - '6050:6050'    
    command: go run main.go

  # PostgreSQL container
  sql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'