services:
  # Go    
  golang:
    container_name: go
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/go/src
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'    
    command: go run main.go
    environment:
      - port=${SERVER_PORT}
      - dbuser=${POSTGRES_USER}
      - dbpassword=${POSTGRES_PASSWORD}
      - dbport=${POSTGRES_PORT}

  # PostgreSQL container
  sql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'